### ISSUE TITLE
doesn't compile on mojave

### ISSUE THREAD

**Issue by fretn** [durgeshtrivedi/imagecluster#1]
I get this error, is it because I need CUDA ?

`Ld /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster normal x86_64 (in target: ImageCluster)
    cd /Users/fretn/Documents/imagecluster
    export MACOSX_DEPLOYMENT_TARGET=10.12
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/fretn/Documents/imagecluster/ImageCluster -L/usr/local/Cellar/opencv/3.4.3 -L/usr/local/Cellar/opencv/3.4.3/.brew -L/usr/local/Cellar/opencv/3.4.3/bin -L/usr/local/Cellar/opencv/3.4.3/include -L/usr/local/Cellar/opencv/3.4.3/lib -L/usr/local/Cellar/opencv/3.4.3/share -L/usr/local/Cellar/opencv/3.4.3/include/opencv -L/usr/local/Cellar/opencv/3.4.3/include/opencv2 -L/usr/local/Cellar/opencv/3.4.3/lib/pkgconfig -L/usr/local/Cellar/opencv/3.4.3/lib/python2.7 -L/usr/local/Cellar/opencv/3.4.3/lib/python3.7 -L/usr/local/Cellar/opencv/3.4.3/share/OpenCV -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/aruco -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/bioinspired -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/calib3d -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/ccalib -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/datasets -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/dnn -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/face -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/features2d -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/flann -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/fuzzy -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/highgui -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/img_hash -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/imgcodecs -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/imgproc -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/line_descriptor -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/ml -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/objdetect -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/optflow -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/phase_unwrapping -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/photo -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/reg -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/rgbd -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/saliency -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/shape -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/stereo -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/stitching -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/structured_light -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/superres -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/surface_matching -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/tracking -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/video -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/videoio -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/videostab -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/xfeatures2d -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/ximgproc -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/xphoto -L/usr/local/Cellar/opencv/3.4.3/lib/python2.7/site-packages -L/usr/local/Cellar/opencv/3.4.3/lib/python3.7/site-packages -L/usr/local/Cellar/opencv/3.4.3/share/OpenCV/haarcascades -L/usr/local/Cellar/opencv/3.4.3/share/OpenCV/lbpcascades -L/usr/local/Cellar/opencv/3.4.3/share/OpenCV/licenses -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/cuda -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/hal -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/opencl -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/utils -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/features2d/hal -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/imgproc/detail -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/imgproc/hal -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/stitching/detail -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/cuda/detail -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/opencl/runtime -L/usr/local/Cellar/opencv/3.4.3/include/opencv2/core/opencl/runtime/autogenerated -L/Users/fretn/Documents/imagecluster/ImageCluster/lib -L/Users/fretn/Documents/imagecluster/ImageCluster/dlib-19.16/build/dlib/ -F/Users/fretn/Documents/imagecluster/ImageCluster -filelist /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster.build/Objects-normal/x86_64/ImageCluster.LinkFileList -mmacosx-version-min=10.12 -Xlinker -object_path_lto -Xlinker /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster.build/Objects-normal/x86_64/ImageCluster_lto.o -stdlib=libc++ -lopencv_calib3d -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videoio -lopencv_videostab -ldlib -ldlib -framework Accelerate -Xlinker -dependency_info -Xlinker /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster.build/Objects-normal/x86_64/ImageCluster_dependency_info.dat -o /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster
Undefined symbols for architecture x86_64:
  "dlib::cpu::tensor_conv::operator()(bool, dlib::resizable_tensor&, dlib::tensor const&, dlib::tensor const&)", referenced from:
      void dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>::forward<dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>::subnet_wrapper>(dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>::subnet_wrapper const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void
>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      void dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>::forward<dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> >(dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::max_pool_<3l, 3l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dli
b::add_layer<dlib::affine_, dlib::add_layer<dlib::con_<32l, 7l, 7l, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150ul, 150ul>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void> const&, dlib::resizable_tensor&) in ImageCluster.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/fretn/Documents/imagecluster/ImageCluster/ImageCluster normal x86_64
(1 failure)`

**Comment by durgeshtrivedi** [comment]
I don't think the issue is with CUDA and  I am sure it doesn't need CUDA. 
It more look like during build the architecture is not set to X86_64 for dlib.
You need to properly set the flags for OpenCV and dlib. if you are building the OpenCV and dlib from source make sure it is build for  X86_64. The dlib and OpenCV flags usually create lot of problem and given error which usually difficult to understand. Right now I don't have MAC and when I created this I not actually tried it on Mojave.
But thanks !! for trying it. If I get the MAC I will try to fix it and it will take time.

**Comment by durgeshtrivedi** [comment]
Fretn add new make file to it.
